name: question-service
services:
  # DATABASE_URL=mongodb://admin:admin@127.0.0.1:27018/?directConnection=true&retryWrites=false&w=majority
  mongodb:
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27018:27017